services:
  - type: web
    name: aurum-pro
    runtime: node
    buildCommand: npm install && npm run build
    publishDirectory: build
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
